package codeofkutulu.mazes;
/**
 * Generated by the random tool, no human has been involved in the process
 * @author johnny
 *
 */
public class TheRandomMap extends Maze {

	final static String[] map = {
		"####.#.U.U.#.####",
		"##.#.w.....w.#.##",
		"#...S..#.#..S...#",
		"###.##.....##.###",
		"##U##.......##U##",
		"##..####.####..##",
		".................",
		"##..####.####..##",
		"##U##.......##U##",
		"###.##.....##.###",
		"#...S..#.#..S...#",
		"##.#.w.....w.#.##",
		"####.#.U.U.#.####"
	};

	@Override
	public String[] getMap(){ return map; }

	public TheRandomMap() {
		super("The random map");
	}
}